# Generated by Django 4.1.6 on 2023-02-14 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percent_off', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('duration', models.CharField(choices=[('once', 'once'), ('repeating', 'repeating'), ('forever', 'forever')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('img', models.ImageField(default='images/default.png', upload_to='images/')),
                ('currency', models.CharField(choices=[('BYN', 'BYN'), ('USD', 'USD')], default='BYN', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BYN', 'BYN'), ('USD', 'USD')], default='BYN', max_length=6)),
                ('discounts', models.ManyToManyField(blank=True, to='stripeApp.discount')),
                ('order_items', models.ManyToManyField(blank=True, to='stripeApp.item')),
            ],
        ),
    ]
